//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavajaValirya {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CadenasTexto {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CadenasTexto() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NavajaValirya.CadenasTexto", typeof(CadenasTexto).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambia a €.
        /// </summary>
        internal static string BCambiarEuros {
            get {
                return ResourceManager.GetString("BCambiarEuros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambia a Ptas..
        /// </summary>
        internal static string BCambiarPtas {
            get {
                return ResourceManager.GetString("BCambiarPtas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de Divisa.
        /// </summary>
        internal static string CambioDivisa {
            get {
                return ResourceManager.GetString("CambioDivisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha producido un error: .
        /// </summary>
        internal static string ErrorException {
            get {
                return ResourceManager.GetString("ErrorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a €..
        /// </summary>
        internal static string Euros {
            get {
                return ResourceManager.GetString("Euros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad: .
        /// </summary>
        internal static string LCantidad {
            get {
                return ResourceManager.GetString("LCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ptas..
        /// </summary>
        internal static string Pesetas {
            get {
                return ResourceManager.GetString("Pesetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cambio son: .
        /// </summary>
        internal static string ResultadoCambio {
            get {
                return ResourceManager.GetString("ResultadoCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No ha introducido valor correcto, por favor, introduzca un número positivo mayor que 0..
        /// </summary>
        internal static string ValorIncorrectoCambioDivisa {
            get {
                return ResourceManager.GetString("ValorIncorrectoCambioDivisa", resourceCulture);
            }
        }
    }
}
